--STEP 2-------------------------
--INSERT INTO Cohort (CohortName) VALUES ('Cohort 34');
--INSERT INTO Cohort (CohortName) VALUES ('Cohort 33');
--INSERT INTO Cohort (CohortName) VALUES ('Cohort 35');
--INSERT INTO Student(Fname, Lname, SlackHandle, CohortId) VALUES ('John', 'Smith', '@js', 1);
--INSERT INTO Student(Fname, Lname, SlackHandle, CohortId) VALUES ('Susie', 'Smith', '@ss', 2);
--INSERT INTO Student(Fname, Lname, SlackHandle, CohortId) VALUES ('Minnie', 'Mouse', '@mm', 1);
--INSERT INTO Student(Fname, Lname, SlackHandle, CohortId) VALUES ('Mickey', 'Mouose', '@mm', 2);
--INSERT INTO Student(Fname, Lname, SlackHandle, CohortId) VALUES ('Donald', 'Duck', '@dd', 3);
--INSERT INTO Student(Fname, Lname, SlackHandle, CohortId) VALUES ('Wiley', 'Coyote', '@wc', 1);
--INSERT INTO Instructor(Fname, Lname, SlackHandle, CohortId, Specialty) VALUES ('Andy', 'Collins', '@ac', 1, 'Singing');
--INSERT INTO Instructor(Fname, Lname, SlackHandle, CohortId, Specialty) VALUES ('Steve', 'Brownlee', '@sb', 3, 'Instructing');
--INSERT INTO Instructor(Fname, Lname, SlackHandle, CohortId, Specialty) VALUES ('Jenna', 'Solis', '@js', 1, 'Coding');
--INSERT INTO Instructor(Fname, Lname, SlackHandle, CohortId, Specialty) VALUES ('Bryan', 'Nilsen', '@bn', 1, 'Basketballing');
--INSERT INTO Instructor(Fname, Lname, SlackHandle, CohortId, Specialty) VALUES ('Jisie', 'David', '@jd', 2, 'CSharping');
--INSERT INTO Exercise (Ename, Elanguage) VALUES ('Nutshell', 'JavaScript');
--INSERT INTO Exercise (Ename, Elanguage) VALUES ('React Nutshell', 'React');
--INSERT INTO Exercise (Ename, Elanguage) VALUES ('Celebrity Tribute', 'HTML');
--INSERT INTO Exercise (Ename, Elanguage) VALUES ('Welcome to Nashville', 'JavaScript');
--INSERT INTO Exercise (Ename, Elanguage) VALUES ('Kennel', 'React');
--INSERT INTO StudentExercise(StudentId, ExerciseId) VALUES ('9', '1');
--INSERT INTO StudentExercise(StudentId, ExerciseId) VALUES ('9', '2');
--INSERT INTO StudentExercise(StudentId, ExerciseId) VALUES ('9', '3');
--INSERT INTO StudentExercise(StudentId, ExerciseId) VALUES ('9', '4');
--INSERT INTO StudentExercise(StudentId, ExerciseId) VALUES ('10', '5');
--INSERT INTO StudentExercise(StudentId, ExerciseId) VALUES ('10', '6');
--INSERT INTO StudentExercise(StudentId, ExerciseId) VALUES ('10', '1');
--INSERT INTO StudentExercise(StudentId, ExerciseId) VALUES ('10', '2');

--STEP 3
--STEP 4
--STEP 6
--STEP 7
--STEP 8